<?php

/*
Should put some doxygen stuff in here
*/
function ord_inventory_help($path, $args) {

	switch ($path) {
		case 'admin/help#ord_inventory':
			return '<p>' . t('temporary help text for now') . '</p>';
		break;
	}

}

//BEGIN THE NODE_MODULE PORTION
function ord_inventory_node_info() {
  return array(
    'ord_inventory_admin' => array(
      'name' => t('Ord Inventory Item'),
      'base' => 'ord_inventory',
      'description' => t('Used to be a page to help manage the back end of the inventory system.'),
      'title_label' => t('Ord Inventory for Admins'),
      'locked' => TRUE, // machine name will be unchangable
    ),
  );
}

function ord_inventory_node_view($node, $view_mode, $langcode) {

  $node->content['my_additional_field'] = array(
    '#markup' => 'what goes here',
    '#weight' => 10,
    '#theme' => 'ord_inventory_my_additional_field',
  );

}

/**
 * Implements hook_menu().
 */
function ord_inventory_menu() {
  $items['ord_inventory/items'] = array(
    'title' => 'Rentals',
    'description' => 'Show a page with a long list across multiple pages',
    'page callback' => 'ord_inventory_page',
    'access callback' => TRUE,
  );
  return $items;
}

function ord_inventory_page() {
  
  //this allows us to sort by these fields
  $header = array(
    array('data' => t('Name'), 'field' => 'd.name'),
    array('data' => t('Description') , 'field' => 'd.description'),
    array('data' => t('Price'), 'field' => 'd.rental_price'),
  );

  // We are extending the PagerDefault class here as well as the TableSort class
  $query = db_select('ord_inventory_items', 'd')->extend('PagerDefault')->extend('TableSort');
  $query->fields('d', array('id', 'description', 'rental_price'));

  $result = $query
    ->limit(10) //change this number to make it page more...
    ->orderByHeader($header)
    ->execute();

  $rows = array();
  foreach ($result as $row) {
    // Normally we would add some nice formatting to our rows
    // but for our purpose we are simply going to add our row
    // to the array.
    $rows[] = array('data' => (array) $row);
  }

  $build['ord_inventory_table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#empty' => t('No items yet'),
  );

  // Attach the pager theme.
  $build['pager_pager'] = array('#theme' => 'pager');

  return $build;
}